### ISSUE TITLE
Deploying to PythonAnywhere manually 신규 챕터 추가

### ISSUE THREAD

**Issue by sujinleeme** [sujinleeme/tutorial-extensions#6]
원 튜토리얼에 [Deploying to PythonAnywhere manually](https://github.com/DjangoGirls/tutorial-extensions/tree/master/en/manual_pythonanywhere_deploy) 챕터가 새로 추가 되었어요. 
@corazzon

**Comment by sujinleeme** [comment]
* 9f46680 원본 내용 추가 및 목차 수정했어요.

**Comment by corazzon** [comment]
@sujinleeme 아직 진행 전이라면 제가 진행할게요.

**Comment by sujinleeme** [comment]
@corazzon 아직 진행하지 않았어요. 감사해요 💖
